version: "3"
services:
  helloworld_react:
    build: 
      context: .
      args:
        REACT_APP_API_ROOT_PROD: https://ready.io/api
        REACT_APP_API_ROOT_DEV: https://conduit.productionready.io/api/
    ports:
      - "80:80"
    # environment:
    #     - "REACT_APP_API_ROOT_PROD=https://productionready.io/api"
